language: java

before_script:
 - cd releng

script: 
 - mvn clean compile install
 
before_deploy:
 - cd ..
 
deploy:
 provider: releases
 api_key: "03a63a5233a1e31d6c4cbe769b8070a47ab5bdbc"
 file_glob: true
 file: 
  - builds/bin/*.zip
  - builds/bin/*.tgz
 skip_cleanup: true

