language: java

before_script:
 - cd releng

script: 
 - mvn clean compile install
 
before_deploy:
 - cd ..
 
deploy:
 provider: releases
 api_key: ${{ secrets.GITHUB_TOKEN }}
 file_glob: true
 file: 
  - builds/bin/*.zip
  - builds/bin/*.tgz
 skip_cleanup: true

