source.. = src/main/java/,\
           src/test/java/
bin.includes = META-INF/,\
               .,\
               lib/,\
               lib/jaxb-runtime.jar,\
               lib/txw2.jar,\
               lib/istack-commons-runtime.jar,\
               lib/stax-ex.jar,\
               lib/FastInfoset.jar
